#include "Syscall.h"
#include <string>
#include <vector>

namespace Syscall {

const std::map<long, SyscallInfo> g_syscall_map = {
    { 0, { "read", 3, { "unsigned int", "char __user *", "size_t" } } },
    { 1, { "write", 3, { "unsigned int", "const char __user *", "size_t" } } },
    { 2, { "open", 3, { "const char __user *", "int", "umode_t" } } },
    { 3, { "close", 1, { "unsigned int" } } },
    { 4, { "stat", 2, { "const char __user *", "struct stat __user *" } } },
    { 5, { "fstat", 2, { "unsigned int", "struct stat __user *" } } },
    { 6, { "lstat", 2, { "const char __user *", "struct stat __user *" } } },
    { 7, { "poll", 3, { "struct pollfd __user *", "unsigned int", "int" } } },
    { 8, { "lseek", 3, { "unsigned int", "off_t", "unsigned int" } } },
    { 9, { "mmap", 6, {  } } },
    { 10, { "mprotect", 3, { "unsigned long", "size_t", "unsigned long" } } },
    { 11, { "munmap", 2, { "unsigned long", "size_t" } } },
    { 12, { "brk", 1, { "unsigned long" } } },
    { 14, { "rt_sigprocmask", 4, { "int", "sigset_t __user *", "sigset_t __user *", "size_t" } } },
    { 17, { "pread64", 4, { "unsigned int", "char __user *", "size_t", "loff_t" } } },
    { 18, { "pwrite64", 4, { "unsigned int", "const char __user *", "size_t", "loff_t" } } },
    { 21, { "access", 2, { "const char __user *", "int" } } },
    { 22, { "pipe", 1, { "int __user *" } } },
    { 23, { "select", 5, { "int", "fd_set __user *", "fd_set __user *", "fd_set __user *", "struct __kernel_old_timeval __user *" } } },
    { 24, { "sched_yield", 0, {  } } },
    { 25, { "mremap", 5, { "unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long" } } },
    { 26, { "msync", 3, { "unsigned long", "size_t", "int" } } },
    { 27, { "mincore", 3, { "unsigned long", "size_t", "unsigned char __user *" } } },
    { 28, { "madvise", 3, { "unsigned long", "size_t", "int" } } },
    { 29, { "shmget", 3, { "key_t", "size_t", "int" } } },
    { 30, { "shmat", 3, { "int", "char __user *", "int" } } },
    { 31, { "shmctl", 3, { "int", "int", "struct shmid_ds __user *" } } },
    { 32, { "dup", 1, { "unsigned int" } } },
    { 33, { "dup2", 2, { "unsigned int", "unsigned int" } } },
    { 34, { "pause", 0, {  } } },
    { 35, { "nanosleep", 2, { "struct __kernel_timespec __user *", "struct __kernel_timespec __user *" } } },
    { 36, { "getitimer", 2, { "int", "struct __kernel_old_itimerval __user *" } } },
    { 37, { "alarm", 1, { "unsigned int" } } },
    { 38, { "setitimer", 3, { "int", "struct __kernel_old_itimerval __user *", "struct __kernel_old_itimerval __user *" } } },
    { 39, { "getpid", 0, {  } } },
    { 40, { "sendfile", 4, { "int", "int", "loff_t __user *", "size_t" } } },
    { 41, { "socket", 3, { "int", "int", "int" } } },
    { 42, { "connect", 3, { "int", "struct sockaddr __user", "int" } } },
    { 43, { "accept", 3, { "int", "struct sockaddr __user", "int __user" } } },
    { 44, { "sendto", 6, { "int", "void __user", "size_t", "unsigned", "struct sockaddr __user", "int" } } },
    { 48, { "shutdown", 2, { "int", "int" } } },
    { 49, { "bind", 3, { "int", "struct sockaddr __user", "int" } } },
    { 50, { "listen", 2, { "int", "int" } } },
    { 51, { "getsockname", 3, { "int", "struct sockaddr __user", "int __user" } } },
    { 52, { "getpeername", 3, { "int", "struct sockaddr __user", "int __user" } } },
    { 53, { "socketpair", 4, { "int", "int", "int", "int __user" } } },
    { 56, { "clone", 5, { "unsigned", "unsigned", "int __user", "int __user", "unsigned" } } },
    { 57, { "fork", 0, {  } } },
    { 58, { "vfork", 0, {  } } },
    { 60, { "exit", 1, { "int" } } },
    { 61, { "wait4", 4, { "pid_t", "int __user *", "int", "struct rusage __user *" } } },
    { 62, { "kill", 2, { "pid_t", "int" } } },
    { 63, { "uname", 1, { "struct new_utsname __user *" } } },
    { 64, { "semget", 3, { "key_t", "int", "int" } } },
    { 65, { "semop", 3, { "int", "struct sembuf __user *", "unsigned" } } },
    { 66, { "semctl", 4, { "int", "int", "int", "unsigned long" } } },
    { 67, { "shmdt", 1, { "char __user *" } } },
    { 68, { "msgget", 2, { "key_t", "int" } } },
    { 69, { "msgsnd", 4, { "int", "struct msgbuf __user *", "size_t", "int" } } },
    { 70, { "msgrcv", 5, { "int", "struct msgbuf __user *", "size_t", "long", "int" } } },
    { 71, { "msgctl", 3, { "int", "int", "struct msqid_ds __user *" } } },
    { 72, { "fcntl", 3, { "unsigned int", "unsigned int", "unsigned long" } } },
    { 73, { "flock", 2, { "unsigned int", "unsigned int" } } },
    { 74, { "fsync", 1, { "unsigned int" } } },
    { 75, { "fdatasync", 1, { "unsigned int" } } },
    { 76, { "truncate", 2, { "const char __user *", "long" } } },
    { 77, { "ftruncate", 2, { "unsigned int", "unsigned long" } } },
    { 78, { "getdents", 3, { "unsigned int", "struct linux_dirent __user *", "unsigned int" } } },
    { 79, { "getcwd", 2, { "char __user *", "unsigned long" } } },
    { 80, { "chdir", 1, { "const char __user *" } } },
    { 81, { "fchdir", 1, { "unsigned int" } } },
    { 82, { "rename", 2, { "const char __user *", "const char __user *" } } },
    { 83, { "mkdir", 2, { "const char __user *", "umode_t" } } },
    { 84, { "rmdir", 1, { "const char __user *" } } },
    { 85, { "creat", 2, { "const char __user *", "umode_t" } } },
    { 86, { "link", 2, { "const char __user *", "const char __user *" } } },
    { 87, { "unlink", 1, { "const char __user *" } } },
    { 88, { "symlink", 2, { "const char __user *", "const char __user *" } } },
    { 89, { "readlink", 3, { "const char __user *", "char __user *", "int" } } },
    { 90, { "chmod", 2, { "const char __user *", "umode_t" } } },
    { 91, { "fchmod", 2, { "unsigned int", "umode_t" } } },
    { 92, { "chown", 3, { "const char __user *", "uid_t", "gid_t" } } },
    { 93, { "fchown", 3, { "unsigned int", "uid_t", "gid_t" } } },
    { 94, { "lchown", 3, { "const char __user *", "uid_t", "gid_t" } } },
    { 95, { "umask", 1, { "int" } } },
    { 96, { "gettimeofday", 2, { "struct __kernel_old_timeval __user *", "struct timezone __user *" } } },
    { 97, { "getrlimit", 2, { "unsigned int", "struct rlimit __user *" } } },
    { 98, { "getrusage", 2, { "int", "struct rusage __user *" } } },
    { 99, { "sysinfo", 1, { "struct sysinfo __user *" } } },
    { 100, { "times", 1, { "struct tms __user *" } } },
    { 102, { "getuid", 0, {  } } },
    { 103, { "syslog", 3, { "int", "char __user *", "int" } } },
    { 104, { "getgid", 0, {  } } },
    { 105, { "setuid", 1, { "uid_t" } } },
    { 106, { "setgid", 1, { "gid_t" } } },
    { 107, { "geteuid", 0, {  } } },
    { 108, { "getegid", 0, {  } } },
    { 109, { "setpgid", 2, { "pid_t", "pid_t" } } },
    { 110, { "getppid", 0, {  } } },
    { 111, { "getpgrp", 0, {  } } },
    { 112, { "setsid", 0, {  } } },
    { 113, { "setreuid", 2, { "uid_t", "uid_t" } } },
    { 114, { "setregid", 2, { "gid_t", "gid_t" } } },
    { 115, { "getgroups", 2, { "int", "gid_t __user *" } } },
    { 116, { "setgroups", 2, { "int", "gid_t __user *" } } },
    { 117, { "setresuid", 3, { "uid_t", "uid_t", "uid_t" } } },
    { 118, { "getresuid", 3, { "uid_t __user *", "uid_t __user *", "uid_t __user *" } } },
    { 119, { "setresgid", 3, { "gid_t", "gid_t", "gid_t" } } },
    { 120, { "getresgid", 3, { "gid_t __user *", "gid_t __user *", "gid_t __user *" } } },
    { 121, { "getpgid", 1, { "pid_t" } } },
    { 122, { "setfsuid", 1, { "uid_t" } } },
    { 123, { "setfsgid", 1, { "gid_t" } } },
    { 124, { "getsid", 1, { "pid_t" } } },
    { 125, { "capget", 2, { "cap_user_header_t", "cap_user_data_t" } } },
    { 126, { "capset", 2, { "cap_user_header_t", "const cap_user_data_t" } } },
    { 130, { "rt_sigsuspend", 2, { "sigset_t __user *", "size_t" } } },
    { 132, { "utime", 2, { "char __user *", "struct utimbuf __user *" } } },
    { 133, { "mknod", 3, { "const char __user *", "umode_t", "unsigned" } } },
    { 135, { "personality", 1, { "unsigned int" } } },
    { 136, { "ustat", 2, { "unsigned", "struct ustat __user *" } } },
    { 137, { "statfs", 2, { "const char __user *", "struct statfs __user *" } } },
    { 138, { "fstatfs", 2, { "unsigned int", "struct statfs __user *" } } },
    { 139, { "sysfs", 3, { "int", "unsigned long", "unsigned long" } } },
    { 140, { "getpriority", 2, { "int", "int" } } },
    { 141, { "setpriority", 3, { "int", "int", "int" } } },
    { 142, { "sched_setparam", 2, { "pid_t", "struct sched_param __user *" } } },
    { 143, { "sched_getparam", 2, { "pid_t", "struct sched_param __user *" } } },
    { 144, { "sched_setscheduler", 3, { "pid_t", "int", "struct sched_param __user *" } } },
    { 145, { "sched_getscheduler", 1, { "pid_t" } } },
    { 146, { "sched_get_priority_max", 1, { "int" } } },
    { 147, { "sched_get_priority_min", 1, { "int" } } },
    { 148, { "sched_rr_get_interval", 2, { "pid_t", "struct __kernel_timespec __user *" } } },
    { 149, { "mlock", 2, { "unsigned long", "size_t" } } },
    { 150, { "munlock", 2, { "unsigned long", "size_t" } } },
    { 151, { "mlockall", 1, { "int" } } },
    { 152, { "munlockall", 0, {  } } },
    { 153, { "vhangup", 0, {  } } },
    { 154, { "modify_ldt", 6, {  } } },
    { 155, { "pivot_root", 2, { "const char __user *", "const char __user *" } } },
    { 156, { "_sysctl", 0, {  } } },
    { 157, { "prctl", 5, { "int", "unsigned long", "unsigned long", "unsigned long", "unsigned long" } } },
    { 158, { "arch_prctl", 6, {  } } },
    { 159, { "adjtimex", 1, { "struct __kernel_timex __user *" } } },
    { 160, { "setrlimit", 2, { "unsigned int", "struct rlimit __user *" } } },
    { 161, { "chroot", 1, { "const char __user *" } } },
    { 162, { "sync", 0, {  } } },
    { 163, { "acct", 1, { "const char __user *" } } },
    { 164, { "settimeofday", 2, { "struct __kernel_old_timeval __user *", "struct timezone __user *" } } },
    { 165, { "mount", 5, { "char __user *", "char __user *", "char __user *", "unsigned long", "void __user *" } } },
    { 166, { "umount2", 2, { "char __user *", "int" } } },
    { 167, { "swapon", 2, { "const char __user *", "int" } } },
    { 168, { "swapoff", 1, { "const char __user *" } } },
    { 169, { "reboot", 4, { "int", "int", "unsigned int", "void __user *" } } },
    { 170, { "sethostname", 2, { "char __user *", "int" } } },
    { 171, { "setdomainname", 2, { "char __user *", "int" } } },
    { 172, { "iopl", 6, {  } } },
    { 173, { "ioperm", 3, { "unsigned long", "unsigned long", "int" } } },
    { 175, { "init_module", 3, { "void __user *", "unsigned long", "const char __user *" } } },
    { 176, { "delete_module", 2, { "const char __user *", "unsigned int" } } },
    { 179, { "quotactl", 4, { "unsigned int", "const char __user *", "qid_t", "void __user *" } } },
    { 186, { "gettid", 0, {  } } },
    { 187, { "readahead", 3, { "int", "loff_t", "size_t" } } },
    { 188, { "setxattr", 5, { "const char __user *", "const char __user *", "const void __user *", "size_t", "int" } } },
    { 189, { "lsetxattr", 5, { "const char __user *", "const char __user *", "const void __user *", "size_t", "int" } } },
    { 190, { "fsetxattr", 5, { "int", "const char __user *", "const void __user *", "size_t", "int" } } },
    { 191, { "getxattr", 4, { "const char __user *", "const char __user *", "void __user *", "size_t" } } },
    { 192, { "lgetxattr", 4, { "const char __user *", "const char __user *", "void __user *", "size_t" } } },
    { 193, { "fgetxattr", 4, { "int", "const char __user *", "void __user *", "size_t" } } },
    { 194, { "listxattr", 3, { "const char __user *", "char __user *", "size_t" } } },
    { 195, { "llistxattr", 3, { "const char __user *", "char __user *", "size_t" } } },
    { 196, { "flistxattr", 3, { "int", "char __user *", "size_t" } } },
    { 197, { "removexattr", 2, { "const char __user *", "const char __user *" } } },
    { 198, { "lremovexattr", 2, { "const char __user *", "const char __user *" } } },
    { 199, { "fremovexattr", 2, { "int", "const char __user *" } } },
    { 200, { "tkill", 2, { "pid_t", "int" } } },
    { 201, { "time", 1, { "__kernel_old_time_t __user *" } } },
    { 202, { "futex", 6, { "u32 __user *", "int", "u32", "const struct __kernel_timespec __user *", "u32 __user *", "u32" } } },
    { 203, { "sched_setaffinity", 3, { "pid_t", "unsigned int", "unsigned long __user *" } } },
    { 204, { "sched_getaffinity", 3, { "pid_t", "unsigned int", "unsigned long __user *" } } },
    { 207, { "io_destroy", 1, { "aio_context_t" } } },
    { 208, { "io_getevents", 5, { "aio_context_t", "long", "long", "struct io_event __user *", "struct __kernel_timespec __user *" } } },
    { 210, { "io_cancel", 3, { "aio_context_t", "struct iocb __user *", "struct io_event __user *" } } },
    { 212, { "lookup_dcookie", 3, { "u64", "char __user *", "size_t" } } },
    { 213, { "epoll_create", 1, { "int" } } },
    { 216, { "remap_file_pages", 5, { "unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long" } } },
    { 217, { "getdents64", 3, { "unsigned int", "struct linux_dirent64 __user *", "unsigned int" } } },
    { 218, { "set_tid_address", 1, { "int __user *" } } },
    { 219, { "restart_syscall", 0, {  } } },
    { 220, { "semtimedop", 4, { "int", "struct sembuf __user *", "unsigned", "const struct __kernel_timespec __user *" } } },
    { 221, { "fadvise64", 4, { "int", "loff_t", "size_t", "int" } } },
    { 223, { "timer_settime", 4, { "timer_t", "int", "const struct __kernel_itimerspec __user *", "struct __kernel_itimerspec __user *" } } },
    { 224, { "timer_gettime", 2, { "timer_t", "struct __kernel_itimerspec __user *" } } },
    { 225, { "timer_getoverrun", 1, { "timer_t" } } },
    { 226, { "timer_delete", 1, { "timer_t" } } },
    { 227, { "clock_settime", 2, { "clockid_t", "const struct __kernel_timespec __user *" } } },
    { 228, { "clock_gettime", 2, { "clockid_t", "struct __kernel_timespec __user *" } } },
    { 229, { "clock_getres", 2, { "clockid_t", "struct __kernel_timespec __user *" } } },
    { 230, { "clock_nanosleep", 4, { "clockid_t", "int", "const struct __kernel_timespec __user *", "struct __kernel_timespec __user *" } } },
    { 231, { "exit_group", 1, { "int" } } },
    { 232, { "epoll_wait", 4, { "int", "struct epoll_event __user *", "int", "int" } } },
    { 233, { "epoll_ctl", 4, { "int", "int", "int", "struct epoll_event __user *" } } },
    { 234, { "tgkill", 3, { "pid_t", "pid_t", "int" } } },
    { 235, { "utimes", 2, { "char __user *", "struct __kernel_old_timeval __user *" } } },
    { 237, { "mbind", 6, { "unsigned long", "unsigned long", "unsigned long", "const unsigned long __user *", "unsigned long", "unsigned" } } },
    { 238, { "set_mempolicy", 3, { "int", "const unsigned long __user *", "unsigned long" } } },
    { 239, { "get_mempolicy", 5, { "int __user *", "unsigned long __user *", "unsigned long", "unsigned long", "unsigned long" } } },
    { 240, { "mq_open", 4, { "const char __user *", "int", "umode_t", "struct mq_attr __user *" } } },
    { 241, { "mq_unlink", 1, { "const char __user *" } } },
    { 242, { "mq_timedsend", 5, { "mqd_t", "const char __user *", "size_t", "unsigned int", "const struct __kernel_timespec __user *" } } },
    { 243, { "mq_timedreceive", 5, { "mqd_t", "char __user *", "size_t", "unsigned int __user *", "const struct __kernel_timespec __user *" } } },
    { 245, { "mq_getsetattr", 3, { "mqd_t", "const struct mq_attr __user *", "struct mq_attr __user *" } } },
    { 248, { "add_key", 5, { "const char __user *", "const char __user *", "const void __user *", "size_t", "key_serial_t" } } },
    { 249, { "request_key", 4, { "const char __user *", "const char __user *", "const char __user *", "key_serial_t" } } },
    { 250, { "keyctl", 5, { "int", "unsigned long", "unsigned long", "unsigned long", "unsigned long" } } },
    { 251, { "ioprio_set", 3, { "int", "int", "int" } } },
    { 252, { "ioprio_get", 2, { "int", "int" } } },
    { 253, { "inotify_init", 0, {  } } },
    { 254, { "inotify_add_watch", 3, { "int", "const char __user *", "u32" } } },
    { 255, { "inotify_rm_watch", 2, { "int", "__s32" } } },
    { 256, { "migrate_pages", 4, { "pid_t", "unsigned long", "const unsigned long __user *", "const unsigned long __user *" } } },
    { 257, { "openat", 4, { "int", "const char __user *", "int", "umode_t" } } },
    { 258, { "mkdirat", 3, { "int", "const char __user *", "umode_t" } } },
    { 259, { "mknodat", 4, { "int", "const char __user *", "umode_t", "unsigned" } } },
    { 260, { "fchownat", 5, { "int", "const char __user *", "uid_t", "gid_t", "int" } } },
    { 261, { "futimesat", 3, { "int", "const char __user *", "struct __kernel_old_timeval __user *" } } },
    { 262, { "newfstatat", 4, { "int", "const char __user *", "struct stat __user *", "int" } } },
    { 263, { "unlinkat", 3, { "int", "const char __user *", "int" } } },
    { 264, { "renameat", 4, { "int", "const char __user *", "int", "const char __user *" } } },
    { 265, { "linkat", 5, { "int", "const char __user *", "int", "const char __user *", "int" } } },
    { 266, { "symlinkat", 3, { "const char __user *", "int", "const char __user *" } } },
    { 267, { "readlinkat", 4, { "int", "const char __user *", "char __user *", "int" } } },
    { 268, { "fchmodat", 3, { "int", "const char __user *", "umode_t" } } },
    { 269, { "faccessat", 3, { "int", "const char __user *", "int" } } },
    { 270, { "pselect6", 6, { "int", "fd_set __user", "fd_set __user", "fd_set __user", "struct __kernel_timespec __user", "void __user" } } },
    { 271, { "ppoll", 5, { "struct pollfd __user", "unsigned", "struct __kernel_timespec __user", "const sigset_t __user", "size_t" } } },
    { 272, { "unshare", 1, { "unsigned long" } } },
    { 275, { "splice", 6, { "int", "loff_t __user *", "int", "loff_t __user *", "size_t", "unsigned int" } } },
    { 276, { "tee", 4, { "int", "int", "size_t", "unsigned int" } } },
    { 277, { "sync_file_range", 4, { "int", "loff_t", "loff_t", "unsigned int" } } },
    { 280, { "utimensat", 4, { "int", "const char __user *", "struct __kernel_timespec __user *", "int" } } },
    { 281, { "epoll_pwait", 6, { "int", "struct epoll_event __user *", "int", "int", "const sigset_t __user *", "size_t" } } },
    { 282, { "signalfd", 3, { "int", "sigset_t __user *", "size_t" } } },
    { 283, { "timerfd_create", 2, { "int", "int" } } },
    { 284, { "eventfd", 1, { "unsigned int" } } },
    { 285, { "fallocate", 4, { "int", "int", "loff_t", "loff_t" } } },
    { 286, { "timerfd_settime", 4, { "int", "int", "const struct __kernel_itimerspec __user *", "struct __kernel_itimerspec __user *" } } },
    { 287, { "timerfd_gettime", 2, { "int", "struct __kernel_itimerspec __user *" } } },
    { 288, { "accept4", 4, { "int", "struct sockaddr __user", "int __user", "int" } } },
    { 289, { "signalfd4", 4, { "int", "sigset_t __user *", "size_t", "int" } } },
    { 290, { "eventfd2", 2, { "unsigned int", "int" } } },
    { 291, { "epoll_create1", 1, { "int" } } },
    { 292, { "dup3", 3, { "unsigned int", "unsigned int", "int" } } },
    { 293, { "pipe2", 2, { "int __user *", "int" } } },
    { 294, { "inotify_init1", 1, { "int" } } },
    { 298, { "perf_event_open", 5, { "struct perf_event_attr __user *", "pid_t", "int", "int", "unsigned long" } } },
    { 300, { "fanotify_init", 2, { "unsigned int", "unsigned int" } } },
    { 301, { "fanotify_mark", 5, { "int", "unsigned int", "u64", "int", "const char __user *" } } },
    { 302, { "prlimit64", 4, { "pid_t", "unsigned int", "const struct rlimit64 __user *", "struct rlimit64 __user *" } } },
    { 303, { "name_to_handle_at", 5, { "int", "const char __user *", "struct file_handle __user *", "int __user *", "int" } } },
    { 304, { "open_by_handle_at", 3, { "int", "struct file_handle __user *", "int" } } },
    { 305, { "clock_adjtime", 2, { "clockid_t", "struct __kernel_timex __user *" } } },
    { 306, { "syncfs", 1, { "int" } } },
    { 308, { "setns", 2, { "int", "int" } } },
    { 309, { "getcpu", 3, { "unsigned __user *", "unsigned __user *", "struct getcpu_cache __user *" } } },
    { 312, { "kcmp", 5, { "pid_t", "pid_t", "int", "unsigned long", "unsigned long" } } },
    { 313, { "finit_module", 3, { "int", "const char __user *", "int" } } },
    { 314, { "sched_setattr", 3, { "pid_t", "struct sched_attr __user *", "unsigned int" } } },
    { 315, { "sched_getattr", 4, { "pid_t", "struct sched_attr __user *", "unsigned int", "unsigned int" } } },
    { 316, { "renameat2", 5, { "int", "const char __user *", "int", "const char __user *", "unsigned int" } } },
    { 317, { "seccomp", 3, { "unsigned int", "unsigned int", "void __user *" } } },
    { 318, { "getrandom", 3, { "char __user *", "size_t", "unsigned int" } } },
    { 319, { "memfd_create", 2, { "const char __user *", "unsigned int" } } },
    { 320, { "kexec_file_load", 5, { "int", "int", "unsigned long", "const char __user *", "unsigned long" } } },
    { 321, { "bpf", 3, { "int", "union bpf_attr *", "unsigned int" } } },
    { 323, { "userfaultfd", 1, { "int" } } },
    { 324, { "membarrier", 3, { "int", "unsigned int", "int" } } },
    { 325, { "mlock2", 3, { "unsigned long", "size_t", "int" } } },
    { 326, { "copy_file_range", 6, { "int", "loff_t __user *", "int", "loff_t __user *", "size_t", "unsigned int" } } },
    { 329, { "pkey_mprotect", 4, { "unsigned long", "size_t", "unsigned long", "int" } } },
    { 330, { "pkey_alloc", 2, { "unsigned long", "unsigned long" } } },
    { 331, { "pkey_free", 1, { "int" } } },
    { 332, { "statx", 5, { "int", "const char __user *", "unsigned", "unsigned", "struct statx __user *" } } },
    { 333, { "io_pgetevents", 6, { "aio_context_t", "long", "long", "struct io_event __user *", "struct __kernel_timespec __user *", "const struct __aio_sigset *" } } },
    { 334, { "rseq", 4, { "struct rseq __user *", "uint32_t", "int", "uint32_t" } } },
    { 424, { "pidfd_send_signal", 4, { "int", "int", "siginfo_t __user *", "unsigned int" } } },
    { 425, { "io_uring_setup", 2, { "u32", "struct io_uring_params __user *" } } },
    { 426, { "io_uring_enter", 6, { "unsigned int", "u32", "u32", "u32", "const void __user *", "size_t" } } },
    { 427, { "io_uring_register", 4, { "unsigned int", "unsigned int", "void __user *", "unsigned int" } } },
    { 428, { "open_tree", 3, { "int", "const char __user *", "unsigned" } } },
    { 429, { "move_mount", 5, { "int", "const char __user *", "int", "const char __user *", "unsigned int" } } },
    { 430, { "fsopen", 2, { "const char __user *", "unsigned int" } } },
    { 431, { "fsconfig", 5, { "int", "unsigned int", "const char __user *", "const void __user *", "int" } } },
    { 432, { "fsmount", 3, { "int", "unsigned int", "unsigned int" } } },
    { 433, { "fspick", 3, { "int", "const char __user *", "unsigned int" } } },
    { 434, { "pidfd_open", 2, { "pid_t", "unsigned int" } } },
    { 435, { "clone3", 2, { "struct clone_args __user *", "size_t" } } },
    { 436, { "close_range", 3, { "unsigned int", "unsigned int", "unsigned int" } } },
    { 437, { "openat2", 4, { "int", "const char __user *", "struct open_how *", "size_t" } } },
    { 438, { "pidfd_getfd", 3, { "int", "int", "unsigned int" } } },
    { 439, { "faccessat2", 4, { "int", "const char __user *", "int", "int" } } },
    { 440, { "process_madvise", 5, { "int", "const struct iovec __user *", "size_t", "int", "unsigned int" } } },
    { 441, { "epoll_pwait2", 6, { "int", "struct epoll_event __user *", "int", "const struct __kernel_timespec __user *", "const sigset_t __user *", "size_t" } } },
    { 442, { "mount_setattr", 5, { "int", "const char __user *", "unsigned int", "struct mount_attr __user *", "size_t" } } },
    { 443, { "quotactl_fd", 4, { "unsigned int", "unsigned int", "qid_t", "void __user *" } } },
    { 444, { "landlock_create_ruleset", 3, { "const struct landlock_ruleset_attr __user *", "size_t", "__u32" } } },
    { 445, { "landlock_add_rule", 4, { "int", "enum landlock_rule_type", "const void __user *", "__u32" } } },
    { 446, { "landlock_restrict_self", 2, { "int", "__u32" } } },
    { 447, { "memfd_secret", 1, { "unsigned int" } } },
    { 448, { "process_mrelease", 2, { "int", "unsigned int" } } },
    { 512, { "rt_sigaction", 6, {  } } },
    { 513, { "rt_sigreturn", 6, {  } } },
    { 514, { "ioctl", 6, {  } } },
    { 515, { "readv", 3, { "unsigned long", "const struct iovec __user *", "unsigned long" } } },
    { 516, { "writev", 3, { "unsigned long", "const struct iovec __user *", "unsigned long" } } },
    { 517, { "recvfrom", 6, {  } } },
    { 518, { "sendmsg", 6, {  } } },
    { 519, { "recvmsg", 6, {  } } },
    { 520, { "execve", 6, {  } } },
    { 521, { "ptrace", 6, {  } } },
    { 522, { "rt_sigpending", 6, {  } } },
    { 523, { "rt_sigtimedwait", 6, {  } } },
    { 524, { "rt_sigqueueinfo", 6, {  } } },
    { 525, { "sigaltstack", 6, {  } } },
    { 526, { "timer_create", 6, {  } } },
    { 527, { "mq_notify", 6, {  } } },
    { 528, { "kexec_load", 6, {  } } },
    { 529, { "waitid", 6, {  } } },
    { 530, { "set_robust_list", 6, {  } } },
    { 531, { "get_robust_list", 6, {  } } },
    { 532, { "vmsplice", 4, { "int", "const struct iovec __user *", "unsigned long", "unsigned int" } } },
    { 533, { "move_pages", 6, { "pid_t", "unsigned long", "const void __user * __user *", "const int __user *", "int __user *", "int" } } },
    { 534, { "preadv", 6, {  } } },
    { 535, { "pwritev", 6, {  } } },
    { 536, { "rt_tgsigqueueinfo", 6, {  } } },
    { 537, { "recvmmsg", 6, {  } } },
    { 538, { "sendmmsg", 6, {  } } },
    { 539, { "process_vm_readv", 6, { "pid_t", "const struct iovec __user *", "unsigned long", "const struct iovec __user *", "unsigned long", "unsigned long" } } },
    { 540, { "process_vm_writev", 6, { "pid_t", "const struct iovec __user *", "unsigned long", "const struct iovec __user *", "unsigned long", "unsigned long" } } },
    { 541, { "setsockopt", 5, { "int", "int", "int", "char __user *", "int" } } },
    { 542, { "getsockopt", 5, { "int", "int", "int", "char __user *", "int __user *" } } },
    { 543, { "io_setup", 6, {  } } },
    { 544, { "io_submit", 6, {  } } },
    { 545, { "execveat", 6, {  } } },
    { 546, { "preadv2", 6, {  } } },
    { 547, { "pwritev2", 6, {  } } },
};

} // namespace Syscall
